spring.application.name=backend
spring.datasource.url=jdbc:postgresql://ep-steep-credit-aob686z6-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_gsT9UcPKIxj4

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
